### ISSUE TITLE
Bot wont start

### ISSUE THREAD

**Issue by vxry3** [tooruu/arabot#87]
![Screenshot 2024-05-12 233629](https://github.com/tooruu/arabot/assets/161689901/bb28c4b6-262f-4f6f-87ac-d98836c837e7)
![Screenshot 2024-05-12 234014](https://github.com/tooruu/arabot/assets/161689901/ec0d1606-e1d8-47bf-9da1-a7c21e104f1f)
![Screenshot 2024-05-12 234158](https://github.com/tooruu/arabot/assets/161689901/9848c53e-f88f-4b6c-b540-5af2aa4406f4)
![Screenshot 2024-05-12 234315](https://github.com/tooruu/arabot/assets/161689901/b9620261-d370-4d73-8c1f-50cbf342ecf2)

**Comment by tooruu** [comment]
You need to run it as a module – `python -m arabot`.
If you need further help to set it up, you can ask here, since I haven't really gotten to writing a proper readme.

**Comment by vxry3** [comment]
> You need to run it as a module – `python -m arabot`. If you need further help to set it up, you can ask here, since I haven't really gotten to writing a proper readme.

got it to work a while back
thanks tho and sorry for a late response
