### ISSUE TITLE
Make schema.prisma accept dynamic data sources instead of static mongodb

### ISSUE THREAD

**Issue by AdiReich** [tooruu/arabot#92]
Please account for users using different data source types in project.

Right now I need to edit schema.prisma after forking the project to adjust for my environment.
During pushing changes I need to be careful not overwriting default schema file to avoid potential issues for other users.

Overall source should be part of configuration, excluded from github pulls.

**Comment by tooruu** [comment]
Not possible as Prisma does not support dynamic db providers.
